function [fitresult, gof] = createFit(degree, mean_spikes)
%CREATEFIT(DEGREE,MEAN_SPIKES)
%  Create a fit.
%
%  Data for 'fitted firing rate' fit:
%      X Input : degree
%      Y Output: mean_spikes
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-May-2017 15:15:21


%% Fit: 'fitted firing rate'.
[xData, yData] = prepareCurveData( degree, mean_spikes );

% Set up fittype and options.
ft = fittype( 'fourier1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0.0196349540849362];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fitted firing rate' );
h = plot( fitresult, xData, yData );
legend( h, 'mean of spikes vs. degree', 'fitted firing rate', 'Location', 'NorthEast' );
% Label axes
xlabel degree
ylabel mean of spikes
grid on


